import { useEffect, useMemo, useState, type FormEvent } from "react";
import type { BookId } from "../data/mockData";
import { api, type KnowledgePoint, type LearnerProfile, type LearnerProfilePayload } from "../services/api";

const domains: Record<BookId, { value: string; label: string }> = { ml: { value: "machine_learning", label: "机器学习" }, dl: { value: "deep_learning", label: "深度学习" } };
const defaultForm = (userId: string, domain: string): LearnerProfilePayload => ({ user_id: userId, learning_domain: domain, background: "", self_assessed_level: "unknown", known_knowledge_point_ids: [], known_knowledge_point_note: "", unknown_knowledge_point_ids: [], current_confusions: "", additional_requirements: "", preferences: { activity_types: ["reading", "quiz"], content_style: "balanced", difficulty: "adaptive", session_duration_minutes: 30, learning_frequency: "flexible" } });

function Choice({ point, selected, onClick }: { point: KnowledgePoint; selected: boolean; onClick: () => void }) {
  return <button type="button" className={`profile-choice ${selected ? "selected" : ""}`} onClick={onClick}><span className="choice-indicator checkbox">{selected ? "✓" : ""}</span><span className="choice-copy"><strong>{point.name}</strong>{point.description && <small>{point.description}</small>}</span></button>;
}

export function LearnerProfileView({ bookId }: { bookId: BookId }) {
  const userId = useMemo(() => new URLSearchParams(window.location.search).get("user_id")?.trim() || "user_001", []);
  const domain = domains[bookId];
  const [form, setForm] = useState<LearnerProfilePayload>(() => defaultForm(userId, domain.value));
  const [existing, setExisting] = useState<LearnerProfile | null>(null);
  const [points, setPoints] = useState<KnowledgePoint[]>([]);
  const [search, setSearch] = useState("");
  const [editing, setEditing] = useState(false);
  const [loading, setLoading] = useState(true);
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState("");
  const [error, setError] = useState("");
  useEffect(() => { let active = true; setLoading(true); setExisting(null); setEditing(false); setError(""); setMessage(""); setSearch(""); setForm(defaultForm(userId, domain.value)); Promise.all([api.getKnowledgePoints(domain.value), api.getLearnerProfile(userId, domain.value)]).then(([catalog, profileResult]) => { if (!active) return; setPoints(catalog.knowledgePoints); if (profileResult.exists && profileResult.profile) { setExisting(profileResult.profile); setForm({ ...profileResult.profile, learning_domain: domain.value }); } }).catch(() => active && setError("无法读取知识点或学习画像，请稍后重试。" )).finally(() => active && setLoading(false)); return () => { active = false; }; }, [domain.value, userId]);
  const update = <K extends keyof LearnerProfilePayload>(key: K, value: LearnerProfilePayload[K]) => setForm((current) => ({ ...current, [key]: value }));
  const toggle = (id: string) => update("known_knowledge_point_ids", form.known_knowledge_point_ids.includes(id) ? form.known_knowledge_point_ids.filter((item) => item !== id) : [...form.known_knowledge_point_ids, id]);
  const filtered = points.filter((point) => `${point.id} ${point.name} ${point.description}`.toLowerCase().includes(search.trim().toLowerCase()));
  const save = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!form.background.trim()) { setError("请填写当前学习背景。"); return; } setBusy(true); setError(""); setMessage(""); const known = new Set(form.known_knowledge_point_ids); const payload: LearnerProfilePayload = { ...form, user_id: userId, learning_domain: domain.value, background: form.background.trim(), unknown_knowledge_point_ids: points.map((point) => point.id).filter((id) => !known.has(id)) }; try { const result = await api.saveLearnerProfile(payload); setExisting(result.profile ?? payload); setForm(result.profile ?? payload); setEditing(false); setMessage(`${domain.label}学习画像已保存。`); } catch (saveError) { setError((saveError as { message?: string })?.message || "保存失败，请稍后重试。"); } finally { setBusy(false); } };
  if (loading) return <div className="page-stack narrow-page"><div className="card profile-loading">正在读取学习画像和知识点目录…</div></div>;
  if (existing && !editing) return <div className="page-stack profile-page"><div className="page-header"><div><span className="eyebrow">学习画像</span><h1>{domain.label}画像已准备好</h1></div></div><div className="card profile-complete-card"><p><strong>已掌握知识点：</strong>{existing.known_knowledge_point_ids.length} 个</p><p><strong>未掌握知识点：</strong>{existing.unknown_knowledge_point_ids.length} 个</p><button className="outline-button" type="button" onClick={() => setEditing(true)}>修改画像</button></div>{(error || message) && <div className="profile-message standalone">{error || message}</div>}</div>;
  return <div className="page-stack profile-page"><div className="page-header"><div><span className="eyebrow">学习起点 · 个性化设置</span><h1>{editing ? "修改" : "建立"}{domain.label}学习画像</h1><p>请选择已经掌握的知识点，未选择的知识点会自动记录为未掌握。</p></div></div><form className="profile-form card" onSubmit={save}><label className="profile-field profile-user-field"><span>用户 ID</span><input value={form.user_id} readOnly /></label><label className="profile-field profile-background-field"><span>当前学习背景</span><textarea value={form.background} onChange={(event) => update("background", event.target.value)} required /></label><section className="profile-section knowledge-point-section"><div className="profile-section-title"><strong>已掌握知识点</strong><span>共 {points.length} 个，已选 {form.known_knowledge_point_ids.length} 个</span></div><input className="knowledge-point-search" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="输入知识点名称或 ID 模糊搜索" /><div className="knowledge-point-picker">{filtered.length ? filtered.map((point) => <Choice key={point.id} point={point} selected={form.known_knowledge_point_ids.includes(point.id)} onClick={() => toggle(point.id)} />) : <div className="knowledge-point-empty">没有匹配的知识点</div>}</div></section><label className="profile-field profile-confusion-field"><span>当前困惑</span><textarea value={form.current_confusions} onChange={(event) => update("current_confusions", event.target.value)} /></label><label className="profile-field profile-requirement-field"><span>其他学习要求</span><textarea value={form.additional_requirements} onChange={(event) => update("additional_requirements", event.target.value)} /></label>{error && <div className="profile-message error">{error}</div>}{message && <div className="profile-message success">{message}</div>}<button className="primary-button profile-submit" type="submit" disabled={busy}>{busy ? "保存中…" : "保存学习画像"}</button></form></div>;
}
