import { useState } from "react";
import { practiceApi, type PracticeAnswerResult, type PracticeQuestion, type PracticeStats } from "../services/api";
import "./practice.css";

export function PracticeView({ bookId, bookTitle, onProgress }: { bookId: string; bookTitle: string; onProgress?: () => void }) {
  const [sessionId,setSessionId]=useState<number|null>(null),[question,setQuestion]=useState<PracticeQuestion|null>(null),[selected,setSelected]=useState(""),[result,setResult]=useState<PracticeAnswerResult|null>(null),[stats,setStats]=useState<PracticeStats>({answerCount:0,correctCount:0,accuracy:0}),[busy,setBusy]=useState(false),[error,setError]=useState(""),[finished,setFinished]=useState(false),[prefetchedQuestion,setPrefetchedQuestion]=useState<PracticeQuestion|null>(null),[prefetchReady,setPrefetchReady]=useState(false);
  const run=async(action:()=>Promise<void>)=>{setBusy(true);setError("");try{await action()}catch(e){setError((e as {message?:string}).message??"操作失败，请稍后重试")}finally{setBusy(false)}};
  const start=()=>run(async()=>{const d=await practiceApi.start(bookId);setSessionId(d.sessionId);setQuestion(d.question);setStats({answerCount:0,correctCount:0,accuracy:0});setSelected("");setResult(null);setFinished(false);setPrefetchedQuestion(null);setPrefetchReady(false)});
  // 提交答案后立即开始取下一题，把原本点击“下一题”后的等待时间提前到反馈阅读阶段。
  const prefetchNext=(activeSessionId:number)=>{setPrefetchReady(false);void practiceApi.next(activeSessionId).then(({question: nextQuestion})=>{setPrefetchedQuestion(nextQuestion);setPrefetchReady(true)}).catch(()=>setPrefetchReady(false))};
  // 每次有效作答落库后通知父页面重新检查勋章，达标时可立即展示弹窗。
  const submit=()=>sessionId&&question&&selected&&run(async()=>{const d=await practiceApi.answer(sessionId,question.id,selected);setResult(d);setStats(d.statistics);onProgress?.();prefetchNext(sessionId)});
  const next=()=>sessionId&&run(async()=>{if(prefetchReady){setQuestion(prefetchedQuestion);setSelected("");setResult(null);setPrefetchedQuestion(null);setPrefetchReady(false);if(!prefetchedQuestion)setFinished(true);return}const d=await practiceApi.next(sessionId);setQuestion(d.question);setSelected("");setResult(null);if(!d.question)setFinished(true)});
  const finish=()=>sessionId&&run(async()=>{const d=await practiceApi.finish(sessionId);setStats(d);setQuestion(null);setFinished(true)});
  if(!sessionId||finished)return <div className="page-stack practice-page"><div className="page-header"><div><span className="eyebrow">PRACTICE · KEEP GOING</span><h1>无限答题</h1><p>从《{bookTitle}》随机抽题，随答随判，答多少由你决定。</p></div></div><section className="card practice-welcome"><div className="practice-mark">∞</div><h2>{finished?"本轮练习完成":"准备好开始了吗？"}</h2>{finished&&<div className="practice-stats"><div><strong>{stats.answerCount}</strong><span>完成题数</span></div><div><strong>{stats.correctCount}</strong><span>答对题数</span></div><div><strong>{stats.accuracy}%</strong><span>正确率</span></div></div>}<p>{finished?"每一次练习都在加深你的知识连接。":"题目不限定数量，你可以随时结束本轮练习。"}</p>{error&&<div className="practice-error">{error}</div>}<button className="primary-button" disabled={busy} onClick={()=>void start()}>{busy?"正在准备…":finished?"再来一轮":"开始答题"}</button></section></div>;
  return <div className="page-stack practice-page"><div className="page-header"><div><span className="eyebrow">{bookTitle}</span><h1>无限答题</h1><p>即时反馈 · 自动记录 · 随时结束</p></div><button className="secondary-button" disabled={busy} onClick={()=>void finish()}>结束本轮</button></div><div className="practice-stats"><div><strong>{stats.answerCount}</strong><span>已答题</span></div><div><strong>{stats.correctCount}</strong><span>答对</span></div><div><strong>{stats.accuracy}%</strong><span>正确率</span></div></div><section className="card practice-question"><div className="practice-meta"><span>第 {stats.answerCount+1} 题</span><small>单选题</small></div><h2>{question?.content}</h2><div className="practice-options">{(question?.options??[]).map((o,i)=>{const key=o.key??o.id??String.fromCharCode(65+i),state=result?(key===result.correctAnswer?"correct":selected===key?"wrong":""):(selected===key?"selected":"");return <button key={key} className={state} disabled={!!result||busy} onClick={()=>setSelected(key)}><b>{key}</b><span>{o.text??o.label}</span></button>})}</div>{result&&<div className={`practice-feedback ${result.correct?"success":"failure"}`}><strong>{result.correct?"回答正确！":`回答错误，正确答案是 ${result.correctAnswer}`}</strong>{result.explanation&&<p>{result.explanation}</p>}</div>}{error&&<div className="practice-error">{error}</div>}<div className="practice-actions"><button className="primary-button" disabled={busy||(!result&&!selected)} onClick={()=>void(result?next():submit())}>{busy?"处理中…":result?"下一题":"提交答案"}</button></div></section></div>;
}
