#!/usr/bin/env python3
"""Turn normalized JSONL learning items into reviewable PostgreSQL seed SQL.

This produces content records and draft task templates only. It intentionally
does not mark imported content as approved or published.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any, Dict, Iterable, List


QUIZ_TASK_MODES = ("diagnostic", "guided_practice", "independent", "retrieval", "remediation", "challenge")
PRACTICE_TASK_MODES = ("guided_practice", "independent", "challenge")
SOURCE_LICENSES = {
    "microsoft-ml-for-beginners": "MIT",
    "microsoft-ai-for-beginners": "MIT",
}


def sql_text(value: Any) -> str:
    if value is None:
        return "NULL"
    return "'" + str(value).replace("'", "''") + "'"


def sql_json(value: Any) -> str:
    return sql_text(json.dumps(value if value is not None else {}, ensure_ascii=False, separators=(",", ":"))) + "::jsonb"


def sql_bool(value: Any) -> str:
    if value is None:
        return "NULL"
    return "TRUE" if bool(value) else "FALSE"


def stable_id(prefix: str, *parts: str) -> str:
    import hashlib
    value = "\x1f".join(parts).encode("utf-8")
    return f"{prefix}-{hashlib.sha256(value).hexdigest()[:20]}"


def sql_mode(value: Any) -> str:
    allowed = {"exact_answer", "code_tests", "notebook_tests", "rubric", "manual_review"}
    return str(value) if value in allowed else "manual_review"


def is_formal_quiz(item: Dict[str, Any]) -> bool:
    source_id = item.get("source", {}).get("source_id")
    return (
        item.get("item_type") == "quiz_question"
        and source_id in {"microsoft-ml-for-beginners", "microsoft-ai-for-beginners"}
        and bool((item.get("answer_data") or {}).get("answer"))
    )


def evaluation_spec(item: Dict[str, Any], formal_quiz: bool) -> Dict[str, Any]:
    """Build a draft evaluator contract; review is required before publication."""
    mode = sql_mode((item.get("metadata") or {}).get("evaluation_mode"))
    if formal_quiz:
        return {
            "mode": "exact_answer",
            "evidence_policy": "direct",
            "config": {
                "submission_field": "selectedOptionKey",
                "comparison_field": "internal_quiz_scoring_bank.correct_option_key",
                "review_answer_source": "learning_item_versions.answer_data.answer",
                "scoring_rule": "selectedOptionKey == correctOptionKey",
            },
        }
    if mode == "code_tests":
        return {
            "mode": mode,
            "evidence_policy": "strong",
            "config": {
                "runner": "unconfigured",
                "requires_validated_tests": True,
                "score_aggregation": "weighted_test_ratio",
            },
        }
    if mode == "notebook_tests":
        return {
            "mode": mode,
            "evidence_policy": "strong",
            "config": {
                "runner": "unconfigured",
                "execute_in_sandbox": True,
                "requires_validated_tests": True,
                "checks": ["execution_success", "hidden_tests", "output_invariants"],
            },
        }
    if mode == "rubric":
        return {
            "mode": mode,
            "evidence_policy": "auxiliary",
            "config": {
                "requires_human_approved_criteria": True,
                "llm_role": "scoring_assistant",
                "human_review_on_low_confidence": True,
            },
        }
    return {
        "mode": "manual_review",
        "evidence_policy": "none",
        "config": {"requires_human_review": True},
    }


def read_items(path: Path) -> List[Dict[str, Any]]:
    return [json.loads(line) for line in path.read_text(encoding="utf-8").splitlines() if line.strip()]


def emit(items: Iterable[Dict[str, Any]]) -> str:
    rows = list(items)
    repositories: Dict[str, Dict[str, Any]] = {}
    documents: Dict[str, Dict[str, Any]] = {}
    for item in rows:
        source = item.get("source", {})
        source_id = source.get("source_id", "unknown-source")
        repositories[source_id] = source
        content_hash = source.get("content_hash") or stable_id("hash", source_id, source.get("file_path", ""))
        document_id = stable_id("doc", source_id, source.get("file_path", ""), content_hash)
        documents[document_id] = {**source, "source_document_id": document_id, "content_hash": content_hash}

    lines = [
        "-- Generated by backend/scripts/emit_catalog_sql.py",
        "-- Imported content remains needs_review/draft until human review.",
        "BEGIN;",
    ]
    for source_id, source in sorted(repositories.items()):
        lines.append(
            "INSERT INTO source_repositories "
            "(source_id, repository_name, repository_url, commit_sha, license_name, metadata) VALUES ("
            f"{sql_text(source_id)}, {sql_text(source.get('repository_name'))}, "
            f"{sql_text(source.get('repository_url'))}, {sql_text(source.get('commit_sha'))}, "
            f"{sql_text(SOURCE_LICENSES.get(source_id))}, "
            f"{sql_json({'imported_by': 'curriculum-importer', 'license_file': 'LICENSE'})}) "
            "ON CONFLICT (source_id) DO UPDATE SET commit_sha=EXCLUDED.commit_sha, "
            "license_name=EXCLUDED.license_name, metadata=EXCLUDED.metadata;"
        )
    for document_id, source in sorted(documents.items()):
        lines.append(
            "INSERT INTO source_documents "
            "(source_document_id, source_id, file_path, file_type, source_url, content_hash, content_version) VALUES ("
            f"{sql_text(document_id)}, {sql_text(source.get('source_id'))}, "
            f"{sql_text(source.get('file_path'))}, {sql_text(Path(source.get('file_path', '')).suffix.lstrip('.'))}, "
            f"{sql_text(source.get('source_url'))}, {sql_text(source.get('content_hash'))}, {sql_text(source.get('commit_sha'))}) "
            "ON CONFLICT (source_document_id) DO NOTHING;"
        )

    for item in rows:
        source = item.get("source", {})
        content_hash = source.get("content_hash") or stable_id("hash", source.get("source_id", ""), source.get("file_path", ""))
        document_id = stable_id("doc", source.get("source_id", ""), source.get("file_path", ""), content_hash)
        item_id = item["learning_item_id"]
        version_id = stable_id("item-version", item_id, "1")
        formal_quiz = is_formal_quiz(item)
        evaluation_mode = sql_mode((item.get("metadata") or {}).get("evaluation_mode"))
        lines.append(
            "INSERT INTO learning_items "
            "(learning_item_id, source_document_id, source_item_key, item_type, title, language, status, assessment_eligible, evaluation_mode, metadata) VALUES ("
            f"{sql_text(item_id)}, {sql_text(document_id)}, {sql_text(item.get('source_item_key'))}, "
            f"{sql_text(item.get('item_type'))}, {sql_text(item.get('title'))}, {sql_text(item.get('language', 'en'))}, "
            f"{sql_text(item.get('status', 'needs_review'))}, {sql_bool(formal_quiz)}, {sql_text(evaluation_mode)}, {sql_json(item.get('metadata', {}))}) "
            "ON CONFLICT (learning_item_id) DO UPDATE SET title=EXCLUDED.title, assessment_eligible=EXCLUDED.assessment_eligible, evaluation_mode=EXCLUDED.evaluation_mode, metadata=EXCLUDED.metadata;"
        )
        answer_data = item.get("answer_data") or {}
        if item.get("knowledge_candidates"):
            answer_data = {**answer_data, "knowledge_candidates": item["knowledge_candidates"]}
        lines.append(
            "INSERT INTO learning_item_versions "
            "(learning_item_version_id, learning_item_id, version_number, stem, answer_data, explanation) VALUES ("
            f"{sql_text(version_id)}, {sql_text(item_id)}, 1, {sql_text(item.get('stem'))}, "
            f"{sql_json(answer_data)}, {sql_text(item.get('explanation'))}) "
            "ON CONFLICT (learning_item_id, version_number) DO NOTHING;"
        )
        lines.append(
            f"UPDATE learning_items SET current_version_id={sql_text(version_id)} "
            f"WHERE learning_item_id={sql_text(item_id)} AND current_version_id IS NULL;"
        )
        for index, option in enumerate(item.get("options", [])):
            option_id = stable_id("option", version_id, str(index), str(option.get("key", "")))
            lines.append(
                "INSERT INTO item_options "
                "(item_option_id, learning_item_version_id, option_key, option_text, is_correct, sort_order) VALUES ("
                f"{sql_text(option_id)}, {sql_text(version_id)}, {sql_text(option.get('key'))}, "
                f"{sql_text(option.get('text'))}, {sql_bool(option.get('is_correct'))}, {index}) ON CONFLICT (item_option_id) DO NOTHING;"
            )
        spec = evaluation_spec(item, formal_quiz)
        evaluation_spec_id = stable_id("evaluation-spec", version_id, spec["mode"], "1")
        lines.append(
            "INSERT INTO evaluation_specs "
            "(evaluation_spec_id, learning_item_version_id, evaluation_mode, evidence_policy, spec_version, config, status) VALUES ("
            f"{sql_text(evaluation_spec_id)}, {sql_text(version_id)}, {sql_text(spec['mode'])}, "
            f"{sql_text(spec['evidence_policy'])}, 1, {sql_json(spec['config'])}, 'draft') "
            "ON CONFLICT (learning_item_version_id, spec_version) DO NOTHING;"
        )
        for criterion in (item.get("metadata") or {}).get("rubric_candidates", []):
            criterion_id = stable_id(
                "rubric-criterion", evaluation_spec_id,
                str(criterion.get("sort_order", 0)), str(criterion.get("criterion_name", "")),
            )
            lines.append(
                "INSERT INTO evaluation_rubric_criteria "
                "(criterion_id, evaluation_spec_id, criterion_name, description, weight, score_levels, sort_order) VALUES ("
                f"{sql_text(criterion_id)}, {sql_text(evaluation_spec_id)}, {sql_text(criterion.get('criterion_name'))}, "
                f"{sql_text(criterion.get('description'))}, {float(criterion.get('weight', 1.0))}, "
                f"{sql_json(criterion.get('score_levels', {}))}, {int(criterion.get('sort_order', 0))}) "
                "ON CONFLICT (criterion_id) DO NOTHING;"
            )
        task_modes = QUIZ_TASK_MODES if formal_quiz else PRACTICE_TASK_MODES
        for mode in task_modes:
            template_id = stable_id("task-template", item_id, mode)
            lines.append(
                "INSERT INTO task_templates "
                "(task_template_id, learning_item_id, task_mode, task_version_id, status, metadata) VALUES ("
                f"{sql_text(template_id)}, {sql_text(item_id)}, {sql_text(mode)}, {sql_text(version_id)}, 'draft', "
                f"{sql_json({'generated_from': 'curriculum-importer', 'assessment_role': 'formal_quiz' if formal_quiz else 'practice_task'})}) ON CONFLICT (task_template_id) DO NOTHING;"
            )
    lines.extend(["COMMIT;", ""])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(emit(read_items(args.input)), encoding="utf-8")
    print(f"wrote {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
